apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demoapp
  namespace: demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demoapp
  template:
    metadata:
      labels:
        app: python-demoapp
    spec:
      containers:
        - name: web
          image: docker.io/yasdevsec/python-demoapp:v3
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /info
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
