apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoapp
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
images:
  - name: docker.io/yasdevsec/python-demoapp
    newTag: v2
