apiVersion: v1
kind: Service
metadata:
  name: python-demoapp
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: python-demoapp
  ports:
    - name: http
      port: 80
      targetPort: 5000
