apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/98-an/infra.git'
    targetRevision: main
    path: k8s/demoapp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demoapp
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
